### PR TITLE
now that functions are exported, no need to namespace them

### PR DESCRIPTION
**Pull request by cjyetman**
depends on https://github.com/RMI-PACTA/pacta.data.preparation/pull/292
related https://github.com/RMI-PACTA/pacta.data.preparation/issues/275

### CODE REVIEW

**Comment by cjyetman** [comment]
ok... I'll edit this to only use `<package>::<function>`, but not `<package>:::<function>` for unexpected functions

**Comment by jdhoffa** [comment]
Yes absolutely, we should avoid using internal functions.

**Comment by cjyetman** [comment]
it makes some lines really long and functions names absurdly long, but it is more clear

**Comment by jdhoffa** [comment]
> it makes some lines really long and functions names absurdly long, but it is clear

yeah fair enough, I'm generally fine with absurdly long lines if they are explicit. Future me will always appreciate something explaining things to me like I'm 5 over something that is pretty but hard to understand.

**Pull request merged**
