### PR TITLE
save currencies data only to output path

### PR DESCRIPTION
**Pull request by cjyetman**
To avoid writing to the inputs directory, initially save the pre-flight currencies data to an in-memory object and only write it to the outputs directory.

supersedes #100

### CODE REVIEW

**Review by AlexAxthelm — APPROVED** [review]
given the discussion in #100, if we end up saving a copy of "raw inputs to data prep" somewhere, would we want to include a copy of this file there?

I think for reproducibility, it's a good idea to have a copy of the files we used for a particular data prep

**Comment by cjyetman** [comment]
> given the discussion in #100, if we end up saving a copy of "raw inputs to data prep" somewhere, would we want to include a copy of this file there?
> 
> I think for reproducibility, it's a good idea to have a copy of the files we used for a particular data prep

That was the original idea of it... but truth be told, the `currencies.rda` file saved in the "raw inputs" has always been the same exact thing as the `currencies.rda` file saved in the outputs. So, I questioned this too, but I came to the conclusion that the benefit of *not* writing to the inputs folder (e.g. it could potentially be read-only, which is probably preferable and might even be necessary in some context) I think outweighs the benefit of making a duplicate of the file.

**Comment by cjyetman** [comment]
> > given the discussion in #100, if we end up saving a copy of "raw inputs to data prep" somewhere, would we want to include a copy of this file there?
> > I think for reproducibility, it's a good idea to have a copy of the files we used for a particular data prep
> 
> That was the original idea of it... but truth be told, the `currencies.rda` file saved in the "raw inputs" has always been the same exact thing as the `currencies.rda` file saved in the outputs. So, I questioned this too, but I came to the conclusion that the benefit of _not_ writing to the inputs folder (e.g. it could potentially be read-only, which is probably preferable and might even be necessary in some context) I think outweighs the benefit of making a duplicate of the file.

#100 was my thoughts on dealing with this a few days ago, but at the moment it just seems mostly unnecessary

**Comment by cjyetman** [comment]
An alternative (I think maybe you suggested something like this somewhere recent @AlexAxthelm) could be copying all the "inputs" to a separate "archive" directory, versus the "inputs", "outputs", or a temporary directory?

**Comment by AlexAxthelm** [comment]
> An alternative (I think maybe you suggested something like this somewhere recent @AlexAxthelm) could be copying all the "inputs" to a separate "archive" directory, versus the "inputs", "outputs", or a temporary directory?

The naming structure that I've been playing around with is:

- `rawdata` for input files
- `data_prep_inputs` for copies of `rawdata`, and files that are downloaded as part of data prep (currencies, indicies, etc).
- `outputs`

**Comment by cjyetman** [comment]
Since you have something incoming (I think) implementing an optional `copy_data` option, can we merge this and implement the data inputs archiving with that?

**Comment by cjyetman** [comment]
> Since you have something incoming (I think) implementing an optional `copy_data` option, can we merge this and implement the data inputs archiving with that?

or I could implement that separately in a mini-PR?

**Comment by AlexAxthelm** [comment]
Let's merge this one in, and when we add that functionality, we'll add currencies to that then.

**Pull request merged**
