### PR TITLE
update FactSet database connect info

### PR DESCRIPTION
**Pull request by cjyetman**
I don't really know how/when/why these connect details changed, so would be good if @AlexAxthelm and/or @Antoine-Lalechere can validate these changes.

### CODE REVIEW

**Review by Antoine-Lalechere — COMMENTED** [review]
it looks good to me, but I would defer to @AlexAxthelm for that one 

mostly due to this ticket: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/8919?src=WorkItemMention&src-action=artifact_link

**Review by AlexAxthelm — APPROVED** [review]

**Comment by AlexAxthelm** [comment]
Note this is intended to be a short-lived database, and will probably not be available for next round of data prep. I am preparing a PR that will work for a long-term solution.

**Comment by cjyetman** [comment]
closing then... makes sense to wait for the proper details

**Comment by AlexAxthelm** [comment]
Deleting branch, since all of the relevent work has migrated to `workflow.factset`

**Pull request closed without merging**
