### PR TITLE
enable arm64 Docker builds

### LINKED ISSUE #104: consider using a base image that has an arm64 version available
Somewhat oddly, [`rocker/tidyverse`](https://hub.docker.com/r/rocker/tidyverse/tags) does not have an arm64 version available while [`rocker/rstudio`](https://hub.docker.com/r/rocker/rstudio/tags) does. Switching to `rocker/rstudio` (and removing or parameterizing the platform specification `--platform=linux/amd64`) would allow drastically increased performance on arm64 machines, though in this particular comparison some tidyverse packages would need to be installed during the image build process which are currently included "for free" with `rocker/tidyverse`.

https://github.com/RMI-PACTA/workflow.data.preparation/blob/c08b8fb5a139716997ae2c0e83a01757d51a9a2d/Dockerfile#L1

related #95

### PR DESCRIPTION
**Pull request by cjyetman**
closes #104 

Use a base image that has arm64 versions available and do not explicitly set the platform to amd64

RStudio and tidyverse provided by rocker/tidyverse and rocker/rstudio are not strictly necessary (necessary tidyverse R packages are installed anyway as dependencies).
https://hub.docker.com/r/rocker/r-ver/tags

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
I've nearly got the build process for multiarch builds in `workflow.pacta`. (https://github.com/RMI-PACTA/workflow.pacta/pull/41). Suggest pausing this one until that's working as intended.

**Comment by cjyetman** [comment]
> I've nearly got the build process for multiarch builds in `workflow.pacta`. ([RMI-PACTA/workflow.pacta#41](https://github.com/RMI-PACTA/workflow.pacta/pull/41)). Suggest pausing this one until that's working as intended.

How is workflow.pacta relevant to this repo?

**Comment by AlexAxthelm** [comment]
Because when that gets resolved, we can use the same action to do CI builds on this repo (including arm64)

**Comment by cjyetman** [comment]
oh... but this PR isn't about a GH action, it's about running the Dockerfile using `docker-compose up`

**Comment by jdhoffa** [comment]
I don't have context or understand the discussion here, so leave it to @AlexAxthelm to review.

**Comment by cjyetman** [comment]
@AlexAxthelm?

**Review by AlexAxthelm — APPROVED** [review]

**Comment by cjyetman** [comment]
holding in draft because getting/building arm64 linux R packages is still wonky

**Comment by cjyetman** [comment]
closing this as arm64 linux binaries on Public Posit Package Manager is not on the short term roadmap: https://forum.posit.co/t/arm64-binary-packages-for-linux-in-posit-public-package-manager/178514

**Pull request closed without merging**
